# Power BI KPI Tables Preparation

In [3]:
import pandas as pd

df = pd.read_csv('../data/processed/cleaned_retail_data.csv')

## Monthly Sales Summary

In [4]:
monthly_summary = df.groupby(
    ['Year', 'Month', 'MonthName']
).agg({
    'TotalAmount': 'sum',
    'Invoice': 'nunique',
    'Customer ID': 'nunique',
    'Quantity': 'sum'
}).reset_index()

monthly_summary.columns = [
    'Year',
    'Month',
    'MonthName',
    'Revenue',
    'TotalOrders',
    'UniqueCustomers',
    'TotalQuantity'
]

monthly_summary.head()

,Year,Month,MonthName,Revenue,TotalOrders,UniqueCustomers,TotalQuantity
0,2009,12,December,683504.010,1512,955,398660
1,2010,1,January,555802.672,1011,720,370082
2,2010,2,February,504558.956,1104,772,371861
3,2010,3,March,696978.471,1524,1057,502100
4,2010,4,April,591982.002,1329,942,350587

In [5]:
monthly_summary.to_csv(
    '../data/processed/monthly_summary.csv',
    index=False
)

## Country Sales Summary

In [6]:
country_summary = df.groupby('Country').agg({
    'TotalAmount': 'sum',
    'Invoice': 'nunique',
    'Customer ID': 'nunique'
}).reset_index()

country_summary.columns = [
    'Country',
    'Revenue',
    'Orders',
    'Customers'
]

country_summary = country_summary.sort_values(
    by='Revenue',
    ascending=False
)

country_summary.head()

           Country       Revenue  Orders  Customers
38  United Kingdom  1.438923e+07   33541       5350
10            EIRE  6.165705e+05     567          5
24     Netherlands  5.540381e+05     228         22
14         Germany  4.250197e+05     789        107
13          France  3.487690e+05     614         95

In [7]:
country_summary.to_csv(
    '../data/processed/country_summary.csv',
    index=False
)

## Product Performance Summary

In [8]:
product_summary = df.groupby(
    ['StockCode', 'Description']
).agg({
    'Quantity': 'sum',
    'TotalAmount': 'sum',
    'Invoice': 'nunique'
}).reset_index()

product_summary.columns = [
    'StockCode',
    'Description',
    'TotalQuantitySold',
    'Revenue',
    'OrderCount'
]

product_summary = product_summary.sort_values(
    by='Revenue',
    ascending=False
)

product_summary.head()

,StockCode,Description,TotalQuantitySold,Revenue,OrderCount
1862,22423,REGENCY CAKESTAND 3 TIER,24124,277656.25,3317
4751,85123A,WHITE HANGING HEART T-LIGHT HOLDER,91757,247048.01,4888
3283,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,168469.60,1
5309,M,Manual,9384,151777.67,620
4725,85099B,JUMBO BAG RED RETROSPOT,74224,134307.44,2612

In [9]:
product_summary.to_csv(
    '../data/processed/product_summary.csv',
    index=False
)

## Customer Summary

In [10]:
customer_summary = df.groupby('Customer ID').agg({
    'TotalAmount': 'sum',
    'Invoice': 'nunique',
    'Quantity': 'sum',
    'InvoiceDate': ['min', 'max']
})

customer_summary.columns = [
    'TotalSpent',
    'TotalOrders',
    'TotalQuantity',
    'FirstPurchase',
    'LastPurchase'
]

customer_summary = customer_summary.reset_index()

customer_summary.head()

,Customer ID,TotalSpent,TotalOrders,TotalQuantity,FirstPurchase,LastPurchase
0,12346,77556.46,12,74285,2009-12-14 08:34:00,2011-01-18 10:01:00
1,12347,4921.53,8,2967,2010-10-31 14:20:00,2011-12-07 15:52:00
2,12348,2019.40,5,2714,2010-09-27 14:59:00,2011-09-25 13:13:00
3,12349,4428.69,4,1624,2010-04-29 13:20:00,2011-11-21 09:51:00
4,12350,334.40,1,197,2011-02-02 16:01:00,2011-02-02 16:01:00

In [12]:
customer_summary['FirstPurchase'] = pd.to_datetime(
    customer_summary['FirstPurchase']
)

customer_summary['LastPurchase'] = pd.to_datetime(
    customer_summary['LastPurchase']
)

In [13]:
customer_summary['CustomerLifetimeDays'] = (
    customer_summary['LastPurchase']
    - customer_summary['FirstPurchase']
).dt.days

In [14]:
customer_summary.to_csv(
    '../data/processed/customer_summary.csv',
    index=False
)

## Daily Sales

In [17]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

daily_sales = df.groupby(
    df['InvoiceDate'].dt.date
).agg({
    'TotalAmount': 'sum'
}).reset_index()

daily_sales.columns = ['Date', 'Revenue']

daily_sales.head()

         Date   Revenue
0  2009-12-01  43894.87
1  2009-12-02  52762.06
2  2009-12-03  67413.62
3  2009-12-04  33913.81
4  2009-12-05   9803.05

In [18]:
daily_sales.to_csv(
    '../data/processed/daily_sales.csv',
    index=False
)